insert into announcement (announcement_id, author, title, description) values (1, 50, 'Blood drive on 3/15/2022 at 9am', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (2, 29, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (3, 12, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (4, 49, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (5, 96, 'Blood drive on 3/15/2022 at 9am', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (6, 6, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (7, 104, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (8, 86, 'Emergency blood supply needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (9, 45, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (10, 45, 'Blood bank closed on 7/4/2022', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (11, 33, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (12, 54, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (13, 83, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (14, 37, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (15, 4, 'Blood drive on 3/15/2022 at 9am', 'give life!');
insert into announcement (announcement_id, author, title, description) values (16, 28, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (17, 63, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (18, 54, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (19, 40, 'Blood bank closed on 7/4/2022', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (20, 26, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (21, 16, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (22, 115, 'Blood bank closed on 7/4/2022', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (23, 30, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (24, 57, 'Blood bank closed on 7/4/2022', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (25, 84, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (26, 12, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (27, 69, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (28, 61, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (29, 46, 'Blood drive on 3/15/2022 at 9am', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (30, 13, 'Emergency blood supply needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (31, 2, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (32, 96, 'Blood drive on 3/15/2022 at 9am', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (33, 68, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (34, 23, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (35, 90, 'Blood drive on 3/15/2022 at 9am', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (36, 50, 'Blood drive on 3/15/2022 at 9am', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (37, 82, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (38, 68, 'Blood drive on 3/15/2022 at 9am', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (39, 14, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (40, 50, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (41, 82, 'Blood drive on 3/15/2022 at 9am', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (42, 116, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (43, 59, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (44, 119, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (45, 24, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (46, 12, 'Blood bank closed on 7/4/2022', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (47, 94, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (48, 78, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (49, 40, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (50, 19, 'Emergency blood supply needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (51, 60, 'Blood drive on 3/15/2022 at 9am', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (52, 59, 'Blood drive on 3/15/2022 at 9am', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (53, 93, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (54, 82, 'Blood donation event on 5/10/2022 at 2pm', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (55, 48, 'Blood donation event on 5/10/2022 at 2pm', 'give life!');
insert into announcement (announcement_id, author, title, description) values (56, 6, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (57, 49, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (58, 12, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (59, 21, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (60, 117, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (61, 114, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (62, 56, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (63, 67, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (64, 44, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (65, 115, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (66, 69, 'Blood drive on 3/15/2022 at 9am', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (67, 8, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (68, 9, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (69, 75, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (70, 80, 'Blood drive on 3/15/2022 at 9am', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (71, 91, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (72, 52, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (73, 44, 'Emergency blood supply needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (74, 56, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (75, 18, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (76, 26, 'Blood drive on 3/15/2022 at 9am', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (77, 87, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (78, 80, 'Blood type O+ urgently needed', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (79, 46, 'Emergency blood supply needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (80, 11, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (81, 23, 'Emergency blood supply needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (82, 44, 'Blood donation event on 5/10/2022 at 2pm', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (83, 89, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (84, 51, 'Blood donation event on 5/10/2022 at 2pm', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (85, 48, 'Blood drive on 3/15/2022 at 9am', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (86, 103, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (87, 82, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (88, 115, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (89, 96, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (90, 89, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (91, 28, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (92, 120, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (93, 22, 'Blood bank closed on 7/4/2022', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (94, 2, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (95, 93, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (96, 68, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (97, 31, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (98, 34, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (99, 78, 'Blood drive on 3/15/2022 at 9am', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (100, 67, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (101, 81, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (102, 88, 'Blood type O+ urgently needed', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (103, 93, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (104, 103, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (105, 83, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (106, 81, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (107, 116, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (108, 13, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (109, 59, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (110, 24, 'Blood drive on 3/15/2022 at 9am', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (111, 27, 'Blood type O+ urgently needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (112, 29, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (113, 70, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (114, 100, 'Emergency blood supply needed', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (115, 78, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (116, 50, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (117, 23, 'Blood donation event on 5/10/2022 at 2pm', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (118, 81, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (119, 21, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (120, 1, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (121, 36, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (122, 114, 'Blood drive on 3/15/2022 at 9am', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (123, 115, 'Emergency blood supply needed', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (124, 90, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (125, 72, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (126, 43, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (127, 68, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (128, 81, 'Blood bank closed on 7/4/2022', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (129, 14, 'Blood donation event on 5/10/2022 at 2pm', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (130, 53, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (131, 16, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (132, 71, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (133, 30, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (134, 90, 'Blood bank closed on 7/4/2022', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (135, 20, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (136, 1, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (137, 30, 'Blood drive on 3/15/2022 at 9am', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (138, 66, 'Blood bank closed on 7/4/2022', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (139, 97, 'Blood donation event on 5/10/2022 at 2pm', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (140, 118, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (141, 4, 'Blood drive on 3/15/2022 at 9am', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (142, 51, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (143, 25, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (144, 117, 'Blood drive on 3/15/2022 at 9am', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (145, 118, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (146, 24, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (147, 96, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (148, 76, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (149, 120, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (150, 25, 'Blood bank closed on 7/4/2022', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (151, 43, 'Blood type O+ urgently needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (152, 43, 'Blood bank closed on 7/4/2022', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (153, 33, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (154, 26, 'Blood type O+ urgently needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (155, 46, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (156, 94, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (157, 63, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (158, 15, 'Blood donation event on 5/10/2022 at 2pm', 'give life!');
insert into announcement (announcement_id, author, title, description) values (159, 60, 'Emergency blood supply needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (160, 60, 'Blood type O+ urgently needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (161, 18, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (162, 105, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (163, 28, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (164, 58, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (165, 11, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (166, 36, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (167, 116, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (168, 97, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (169, 75, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (170, 46, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (171, 103, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (172, 47, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (173, 53, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (174, 83, 'Blood type O+ urgently needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (175, 96, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (176, 90, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (177, 94, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (178, 72, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (179, 59, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (180, 111, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (181, 106, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (182, 29, 'Blood drive on 3/15/2022 at 9am', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (183, 79, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (184, 59, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (185, 22, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (186, 36, 'Blood drive on 3/15/2022 at 9am', 'give life!');
insert into announcement (announcement_id, author, title, description) values (187, 54, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (188, 52, 'Emergency blood supply needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (189, 51, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (190, 1, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (191, 44, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (192, 12, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (193, 84, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (194, 65, 'Blood drive on 3/15/2022 at 9am', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (195, 69, 'Blood bank closed on 7/4/2022', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (196, 86, 'Emergency blood supply needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (197, 88, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (198, 13, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (199, 72, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (200, 30, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (201, 103, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (202, 7, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (203, 21, 'Blood bank closed on 7/4/2022', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (204, 18, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (205, 105, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (206, 45, 'Blood drive on 3/15/2022 at 9am', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (207, 44, 'Blood bank closed on 7/4/2022', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (208, 44, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (209, 20, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (210, 52, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (211, 46, 'Blood drive on 3/15/2022 at 9am', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (212, 96, 'Blood drive on 3/15/2022 at 9am', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (213, 117, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (214, 104, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (215, 89, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (216, 50, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (217, 20, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (218, 19, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (219, 57, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (220, 47, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (221, 18, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (222, 80, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (223, 120, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (224, 72, 'Blood donation event on 5/10/2022 at 2pm', 'give life!');
insert into announcement (announcement_id, author, title, description) values (225, 66, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (226, 49, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (227, 63, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (228, 70, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (229, 83, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (230, 22, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (231, 45, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (232, 53, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (233, 49, 'Blood type O+ urgently needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (234, 31, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (235, 30, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (236, 78, 'Blood donation event on 5/10/2022 at 2pm', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (237, 64, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (238, 39, 'Blood drive on 3/15/2022 at 9am', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (239, 2, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (240, 76, 'Blood donation event on 5/10/2022 at 2pm', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (241, 3, 'Blood type O+ urgently needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (242, 44, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (243, 56, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (244, 49, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (245, 43, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (246, 11, 'Blood bank closed on 7/4/2022', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (247, 47, 'Blood type O+ urgently needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (248, 1, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (249, 70, 'Blood drive on 3/15/2022 at 9am', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (250, 103, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (251, 8, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (252, 12, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (253, 12, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (254, 94, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (255, 60, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (256, 111, 'Blood bank closed on 7/4/2022', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (257, 20, 'Blood drive on 3/15/2022 at 9am', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (258, 3, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (259, 14, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (260, 40, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (261, 45, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (262, 82, 'Emergency blood supply needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (263, 21, 'Blood type O+ urgently needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (264, 114, 'Blood drive on 3/15/2022 at 9am', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (265, 64, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (266, 24, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (267, 52, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (268, 4, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (269, 104, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (270, 103, 'Blood drive on 3/15/2022 at 9am', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (271, 93, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (272, 1, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (273, 7, 'Blood donation event on 5/10/2022 at 2pm', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (274, 56, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (275, 45, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (276, 89, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (277, 68, 'Blood type O+ urgently needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (278, 9, 'Blood donation event on 5/10/2022 at 2pm', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (279, 3, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (280, 53, 'Blood donation event on 5/10/2022 at 2pm', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (281, 117, 'Blood drive on 3/15/2022 at 9am', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (282, 46, 'Blood type O+ urgently needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (283, 49, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (284, 44, 'Emergency blood supply needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (285, 106, 'Blood type O+ urgently needed', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (286, 46, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (287, 82, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (288, 87, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (289, 81, 'Blood type O+ urgently needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (290, 21, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (291, 93, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (292, 82, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (293, 54, 'Blood drive on 3/15/2022 at 9am', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (294, 87, 'Emergency blood supply needed', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (295, 103, 'Blood drive on 3/15/2022 at 9am', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (296, 75, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (297, 27, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (298, 35, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (299, 39, 'Blood drive on 3/15/2022 at 9am', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (300, 105, 'Emergency blood supply needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (301, 104, 'Blood bank closed on 7/4/2022', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (302, 21, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (303, 46, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (304, 6, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (305, 63, 'Blood drive on 3/15/2022 at 9am', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (306, 23, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (307, 26, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (308, 96, 'Blood donation event on 5/10/2022 at 2pm', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (309, 47, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (310, 39, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (311, 66, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (312, 76, 'Blood type O+ urgently needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (313, 114, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (314, 39, 'Blood bank closed on 7/4/2022', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (315, 11, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (316, 43, 'Blood type O+ urgently needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (317, 33, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (318, 73, 'Blood type O+ urgently needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (319, 44, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (320, 91, 'Blood drive on 3/15/2022 at 9am', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (321, 13, 'Blood bank closed on 7/4/2022', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (322, 14, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (323, 53, 'Blood donation event on 5/10/2022 at 2pm', 'give life!');
insert into announcement (announcement_id, author, title, description) values (324, 96, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (325, 20, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (326, 94, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (327, 9, 'Blood drive on 3/15/2022 at 9am', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (328, 100, 'Emergency blood supply needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (329, 105, 'Blood type O+ urgently needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (330, 6, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (331, 70, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (332, 114, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (333, 23, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (334, 14, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (335, 52, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (336, 64, 'Blood type O+ urgently needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (337, 52, 'Blood type O+ urgently needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (338, 54, 'Emergency blood supply needed', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (339, 50, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (340, 54, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (341, 96, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (342, 88, 'Blood bank closed on 7/4/2022', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (343, 106, 'Blood donation event on 5/10/2022 at 2pm', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (344, 6, 'Blood donation event on 5/10/2022 at 2pm', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (345, 58, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (346, 67, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (347, 14, 'Blood donation event on 5/10/2022 at 2pm', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (348, 88, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (349, 54, 'Blood type O+ urgently needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (350, 20, 'Blood bank closed on 7/4/2022', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (351, 1, 'Blood bank closed on 7/4/2022', 'give life!');
insert into announcement (announcement_id, author, title, description) values (352, 78, 'Emergency blood supply needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (353, 82, 'Blood bank closed on 7/4/2022', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (354, 56, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (355, 34, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (356, 52, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (357, 19, 'Blood bank closed on 7/4/2022', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (358, 120, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (359, 23, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (360, 71, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (361, 63, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (362, 3, 'Emergency blood supply needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (363, 20, 'Blood type O+ urgently needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (364, 36, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (365, 117, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (366, 21, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (367, 81, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (368, 40, 'Blood bank closed on 7/4/2022', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (369, 23, 'Emergency blood supply needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (370, 53, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (371, 23, 'Blood bank closed on 7/4/2022', 'give life!');
insert into announcement (announcement_id, author, title, description) values (372, 40, 'Blood type O+ urgently needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (373, 33, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (374, 1, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (375, 72, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (376, 72, 'Emergency blood supply needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (377, 21, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (378, 97, 'Emergency blood supply needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (379, 37, 'Blood drive on 3/15/2022 at 9am', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (380, 6, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (381, 43, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (382, 87, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (383, 57, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (384, 3, 'Blood drive on 3/15/2022 at 9am', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (385, 16, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (386, 91, 'Blood drive on 3/15/2022 at 9am', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (387, 64, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (388, 16, 'Blood drive on 3/15/2022 at 9am', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (389, 27, 'Blood type O+ urgently needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (390, 64, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (391, 70, 'Blood type O+ urgently needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (392, 50, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (393, 60, 'Blood drive on 3/15/2022 at 9am', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (394, 35, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (395, 12, 'Blood type O+ urgently needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (396, 111, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (397, 105, 'Blood drive on 3/15/2022 at 9am', 'give life!');
insert into announcement (announcement_id, author, title, description) values (398, 50, 'Blood type O+ urgently needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (399, 60, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (400, 31, 'Blood drive on 3/15/2022 at 9am', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (401, 120, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (402, 37, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (403, 15, 'Emergency blood supply needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (404, 80, 'Blood drive on 3/15/2022 at 9am', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (405, 54, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (406, 78, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (407, 31, 'Blood drive on 3/15/2022 at 9am', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (408, 43, 'Blood type O+ urgently needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (409, 86, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (410, 19, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (411, 67, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (412, 46, 'Blood type O+ urgently needed', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (413, 48, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (414, 58, 'Blood drive on 3/15/2022 at 9am', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (415, 96, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (416, 21, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (417, 31, 'Blood drive on 3/15/2022 at 9am', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (418, 68, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (419, 49, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (420, 49, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (421, 73, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (422, 22, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (423, 72, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (424, 26, 'Emergency blood supply needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (425, 69, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (426, 19, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (427, 117, 'Blood type O+ urgently needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (428, 36, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (429, 80, 'Blood bank closed on 7/4/2022', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (430, 36, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (431, 60, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (432, 45, 'Emergency blood supply needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (433, 76, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (434, 66, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (435, 118, 'Blood bank closed on 7/4/2022', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (436, 88, 'Blood drive on 3/15/2022 at 9am', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (437, 100, 'Blood drive on 3/15/2022 at 9am', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (438, 49, 'Blood donation event on 5/10/2022 at 2pm', 'give life!');
insert into announcement (announcement_id, author, title, description) values (439, 69, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (440, 76, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (441, 71, 'Blood type O+ urgently needed', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (442, 117, 'Blood type O+ urgently needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (443, 34, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (444, 2, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (445, 114, 'Emergency blood supply needed', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (446, 50, 'Blood bank closed on 7/4/2022', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (447, 84, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (448, 2, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (449, 118, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (450, 2, 'Blood drive on 3/15/2022 at 9am', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (451, 115, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (452, 45, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (453, 4, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (454, 70, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (455, 16, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (456, 2, 'Blood donation event on 5/10/2022 at 2pm', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (457, 100, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (458, 36, 'Blood bank closed on 7/4/2022', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (459, 51, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (460, 11, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (461, 22, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (462, 68, 'Emergency blood supply needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (463, 30, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (464, 111, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (465, 103, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (466, 91, 'Emergency blood supply needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (467, 91, 'Blood type O+ urgently needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (468, 29, 'Emergency blood supply needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (469, 24, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (470, 2, 'Emergency blood supply needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (471, 65, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (472, 66, 'Blood bank closed on 7/4/2022', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (473, 31, 'Blood type O+ urgently needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (474, 7, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (475, 94, 'Blood drive on 3/15/2022 at 9am', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (476, 116, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (477, 89, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (478, 80, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (479, 103, 'Blood drive on 3/15/2022 at 9am', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (480, 37, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (481, 82, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (482, 13, 'Blood drive on 3/15/2022 at 9am', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (483, 21, 'Blood type O+ urgently needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (484, 25, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (485, 12, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (486, 46, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (487, 76, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (488, 44, 'Blood type O+ urgently needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (489, 33, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (490, 86, 'Emergency blood supply needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (491, 3, 'Blood bank closed on 7/4/2022', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (492, 9, 'Blood type O+ urgently needed', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (493, 13, 'Blood bank closed on 7/4/2022', 'give life!');
insert into announcement (announcement_id, author, title, description) values (494, 52, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (495, 24, 'Blood type O+ urgently needed', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (496, 25, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (497, 4, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (498, 14, 'Emergency blood supply needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (499, 71, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (500, 84, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (501, 120, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (502, 67, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (503, 78, 'Emergency blood supply needed', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (504, 119, 'Blood type O+ urgently needed', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (505, 78, 'Blood drive on 3/15/2022 at 9am', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (506, 118, 'Blood drive on 3/15/2022 at 9am', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (507, 64, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (508, 36, 'Blood bank closed on 7/4/2022', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (509, 100, 'Blood drive on 3/15/2022 at 9am', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (510, 8, 'Blood drive on 3/15/2022 at 9am', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (511, 94, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (512, 13, 'Blood drive on 3/15/2022 at 9am', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (513, 81, 'Blood donation event on 5/10/2022 at 2pm', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (514, 12, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (515, 97, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (516, 76, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (517, 27, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (518, 8, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (519, 53, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (520, 96, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (521, 97, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (522, 67, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (523, 31, 'Blood donation event on 5/10/2022 at 2pm', 'Blood donation event at the community center!');
insert into announcement (announcement_id, author, title, description) values (524, 16, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (525, 59, 'Blood type O+ urgently needed', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (526, 45, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (527, 27, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (528, 21, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (529, 88, 'Blood type O+ urgently needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (530, 14, 'Blood type O+ urgently needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (531, 25, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (532, 14, 'Blood drive on 3/15/2022 at 9am', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (533, 114, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (534, 21, 'Blood bank closed on 7/4/2022', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (535, 104, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (536, 51, 'Emergency blood supply needed', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (537, 75, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (538, 67, 'Blood bank closed on 7/4/2022', 'Blood donation is a selfless act of kindness!');
insert into announcement (announcement_id, author, title, description) values (539, 19, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (540, 97, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (541, 52, 'Blood drive on 3/15/2022 at 9am', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (542, 2, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (543, 18, 'Blood type O+ urgently needed', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (544, 15, 'Emergency blood supply needed', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (545, 67, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (546, 47, 'Blood drive on 3/15/2022 at 9am', 'give life!');
insert into announcement (announcement_id, author, title, description) values (547, 24, 'Blood bank closed on 7/4/2022', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (548, 14, 'Blood type O+ urgently needed', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (549, 29, 'Blood type O+ urgently needed', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (550, 14, 'Blood donation event on 5/10/2022 at 2pm', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (551, 25, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (552, 91, 'Emergency blood supply needed', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (553, 9, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (554, 64, 'Blood drive on 3/15/2022 at 9am', 'Join us in giving the gift of life!');
insert into announcement (announcement_id, author, title, description) values (555, 46, 'Blood donation event on 5/10/2022 at 2pm', 'give life!');
insert into announcement (announcement_id, author, title, description) values (556, 33, 'Blood donation event on 5/10/2022 at 2pm', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (557, 46, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (558, 63, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (559, 75, 'Blood drive on 3/15/2022 at 9am', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (560, 114, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (561, 45, 'Blood donation event on 5/10/2022 at 2pm', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (562, 79, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (563, 15, 'Blood bank closed on 7/4/2022', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (564, 21, 'Blood bank closed on 7/4/2022', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (565, 83, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (566, 24, 'Emergency blood supply needed', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (567, 52, 'Blood donation event on 5/10/2022 at 2pm', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (568, 79, 'Blood type O+ urgently needed', 'give life!');
insert into announcement (announcement_id, author, title, description) values (569, 116, 'Emergency blood supply needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (570, 27, 'Blood donation event on 5/10/2022 at 2pm', 'Free snacks and drinks for blood donors!');
insert into announcement (announcement_id, author, title, description) values (571, 22, 'Blood donation event on 5/10/2022 at 2pm', 'Help us meet our blood donation goal!');
insert into announcement (announcement_id, author, title, description) values (572, 26, 'Blood donation event on 5/10/2022 at 2pm', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (573, 23, 'Blood donation event on 5/10/2022 at 2pm', 'be a hero today!');
insert into announcement (announcement_id, author, title, description) values (574, 46, 'Blood type O+ urgently needed', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (575, 115, 'Emergency blood supply needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (576, 117, 'Emergency blood supply needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (577, 69, 'Blood donation event on 5/10/2022 at 2pm', 'it''s a small act that can save a life!');
insert into announcement (announcement_id, author, title, description) values (578, 37, 'Blood donation event on 5/10/2022 at 2pm', 'Give blood');
insert into announcement (announcement_id, author, title, description) values (579, 21, 'Blood type O+ urgently needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (580, 18, 'Emergency blood supply needed', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (581, 73, 'Blood donation event on 5/10/2022 at 2pm', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (582, 90, 'Emergency blood supply needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (583, 61, 'Blood bank closed on 7/4/2022', 'New blood bank location now open!');
insert into announcement (announcement_id, author, title, description) values (584, 52, 'Blood drive on 3/15/2022 at 9am', 'Blood drive happening this Saturday!');
insert into announcement (announcement_id, author, title, description) values (585, 111, 'Blood type O+ urgently needed', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (586, 88, 'Blood bank closed on 7/4/2022', 'Blood donation saves lives');
insert into announcement (announcement_id, author, title, description) values (587, 43, 'Blood drive on 3/15/2022 at 9am', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (588, 2, 'Emergency blood supply needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (589, 16, 'Blood donation event on 5/10/2022 at 2pm', 'Become a regular blood donor and make a difference!');
insert into announcement (announcement_id, author, title, description) values (590, 34, 'Blood donation event on 5/10/2022 at 2pm', 'Emergency need for O-negative blood!');
insert into announcement (announcement_id, author, title, description) values (591, 69, 'Blood type O+ urgently needed', 'Donate blood and save lives!');
insert into announcement (announcement_id, author, title, description) values (592, 21, 'Blood drive on 3/15/2022 at 9am', 'Donate blood');
insert into announcement (announcement_id, author, title, description) values (593, 67, 'Blood bank closed on 7/4/2022', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (594, 116, 'Blood donation event on 5/10/2022 at 2pm', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (595, 2, 'Blood drive on 3/15/2022 at 9am', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (596, 111, 'Emergency blood supply needed', 'Join our blood donor registry and help those in need!');
insert into announcement (announcement_id, author, title, description) values (597, 40, 'Blood bank closed on 7/4/2022', 'Blood shortage alert!');
insert into announcement (announcement_id, author, title, description) values (598, 58, 'Blood type O+ urgently needed', 'Your blood donation can make a big impact!');
insert into announcement (announcement_id, author, title, description) values (599, 71, 'Blood bank closed on 7/4/2022', 'Urgent need for platelet donors!');
insert into announcement (announcement_id, author, title, description) values (600, 25, 'Blood bank closed on 7/4/2022', 'Blood donation is a selfless act of kindness!');
